mod commands;
mod types;
mod windows;

use std::sync::Mutex;

use tauri::Manager;

use commands::i18n::LocaleStore;
use commands::notice::NoticeStore;
use commands::widgets::WidgetStore;
use windows::WindowManager;

/// Health check command — returns the app version for frontend verification.
#[tauri::command]
#[specta::specta]
fn health_check(app: tauri::AppHandle) -> String {
    let version = app
        .config()
        .version
        .clone()
        .unwrap_or_else(|| "unknown".to_string());
    format!("AIRI Tauri v{version}")
}

/// Build the tauri-specta type-safe command/event router.
fn build_specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            health_check,
            // Window
            commands::window::window_get_bounds,
            commands::window::window_set_bounds,
            commands::window::window_set_ignore_mouse_events,
            commands::window::window_set_vibrancy,
            commands::window::window_set_background_material,
            commands::window::window_resize,
            commands::window::window_close,
            // Screen
            commands::screen::screen_get_all_displays,
            commands::screen::screen_get_primary_display,
            commands::screen::screen_get_cursor_screen_point,
            commands::screen::screen_dip_to_screen_point,
            commands::screen::screen_dip_to_screen_rect,
            commands::screen::screen_screen_to_dip_point,
            commands::screen::screen_screen_to_dip_rect,
            // Streaming events
            commands::streaming::start_tracking_mouse_position,
            commands::streaming::start_loop_get_bounds,
            commands::streaming::start_dragging_window,
            // App lifecycle
            commands::app::app_quit,
            commands::app::open_main_devtools,
            commands::app::open_settings,
            commands::app::open_chat,
            commands::app::open_devtools_window,
            // Widgets
            commands::widgets::widgets_open_window,
            commands::widgets::widgets_add,
            commands::widgets::widgets_remove,
            commands::widgets::widgets_clear,
            commands::widgets::widgets_update,
            commands::widgets::widgets_fetch,
            commands::widgets::widgets_prepare,
            // Notice
            commands::notice::notice_open,
            commands::notice::notice_action,
            commands::notice::notice_page_mounted,
            commands::notice::notice_page_unmounted,
            // Caption
            commands::caption::caption_get_is_following_window,
            // i18n
            commands::i18n::i18n_set_locale,
            commands::i18n::i18n_get_locale,
        ])
        .events(tauri_specta::collect_events![])
}

/// Register all workspace plugins onto the Tauri Builder.
///
/// Plugins are gated behind feature flags so that heavy dependencies
/// (e.g. ONNX Runtime for audio plugins) can be excluded during
/// development builds for faster compile times.
fn register_plugins(builder: tauri::Builder<tauri::Wry>) -> tauri::Builder<tauri::Wry> {
    let builder = builder.plugin(tauri_plugin_shell::init());
    let builder = builder.plugin(tauri_plugin_http::init());
    let builder = builder.plugin(tauri_plugin_fs::init());
    let builder = builder.plugin(tauri_plugin_window_state::Builder::default().build());

    #[cfg(feature = "plugin-nspanel")]
    let builder = builder.plugin(tauri_nspanel::init());

    #[cfg(feature = "plugin-mcp")]
    let builder = builder.plugin(tauri_plugin_mcp::Builder::default().build());

    #[cfg(feature = "plugin-rdev")]
    let builder = builder.plugin(tauri_plugin_rdev::init());

    #[cfg(feature = "plugin-window-pass-through")]
    let builder =
        builder.plugin(tauri_plugin_window_pass_through_on_hover::init());

    #[cfg(feature = "plugin-window-router-link")]
    let builder = builder.plugin(tauri_plugin_window_router_link::init(
        tauri_plugin_window_router_link::WindowMatcher::new(),
    ));

    #[cfg(feature = "plugin-audio-transcription")]
    let builder =
        builder.plugin(tauri_plugin_ipc_audio_transcription_ort::init());

    #[cfg(feature = "plugin-audio-vad")]
    let builder = builder.plugin(tauri_plugin_ipc_audio_vad_ort::init());

    builder
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let specta_builder = build_specta_builder();

    // Generate TypeScript bindings during development builds
    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// This file is auto-generated by tauri-specta. Do not edit.\n"),
            "../src/generated/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    let builder = tauri::Builder::default();
    let builder = register_plugins(builder);

    builder
        .invoke_handler(specta_builder.invoke_handler())
        .manage(Mutex::new(WidgetStore::new()))
        .manage(Mutex::new(NoticeStore::new()))
        .manage(Mutex::new(LocaleStore::new("en")))
        .setup(move |app| {
            specta_builder.mount_events(app);

            // Initialize the WindowManager and convert the main window to NSPanel
            let window_manager = WindowManager::new(app.handle().clone());
            if let Err(e) = window_manager.create_main_window() {
                log::warn!("Failed to set up main window as panel: {}", e);
            }
            app.manage(Mutex::new(window_manager));

            log::info!(
                "AIRI Tauri app started — version {}",
                app.config()
                    .version
                    .clone()
                    .unwrap_or_else(|| "unknown".to_string())
            );
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running AIRI Tauri application");
}
